/vis/disable
/gate/geometry/setMaterialDatabase GateMaterials.db
/gate/world/geometry/setXLength 1000. mm
/gate/world/geometry/setYLength 1000. mm
/gate/world/geometry/setZLength 1000. mm
/gate/world/vis/setVisible 1
/gate/world/setMaterial Air
/gate/world/daughters/name ecat
/gate/world/daughters/insert cylinder
/gate/ecat/placement/setTranslation 0.0 0.0 0.0 cm
/gate/ecat/geometry/setRmax 50 cm
/gate/ecat/geometry/setRmin 10 cm
/gate/ecat/geometry/setHeight 25 cm
/gate/ecat/setMaterial Air
/gate/ecat/vis/forceWireframe
/gate/ecat/vis/setColor red
/gate/ecat/daughters/name block
/gate/ecat/daughters/insert box
/gate/block/placement/setTranslation 20.0 0.0 0.0 cm
/gate/block/geometry/setXLength 3 cm
/gate/block/geometry/setYLength 1 cm
/gate/block/geometry/setZLength 1 cm
/gate/block/setMaterial Air
/gate/ecat/daughters/name crystal
/gate/ecat/daughters/insert box
/gate/crystal/geometry/setXLength 3 cm
/gate/crystal/geometry/setYLength 1 cm
/gate/crystal/geometry/setZLength 1 cm
/gate/crystal/placement/setTranslation 20. 0. 0. cm
/gate/crystal/setMaterial LSO
/gate/crystal/vis/setColor green
/gate/crystal/vis/setVisible 1
/gate/systems/ecat/block/attach block
/gate/systems/ecat/crystal/attach crystal
/gate/crystal/attachCrystalSD
/gate/systems/ecat/describe

/gate/physics/addPhysicsList emstandard_opt3
/gate/physics/processList Enabled
/gate/physics/processList Initialized
/gate/physics/Gamma/SetCutInRegion world 1 mm
/gate/physics/Electron/SetCutInRegion world 1 mm
/gate/physics/displayCuts

/gate/run/initialize
/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/adder/positionPolicy energyWeightedCentroid
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setPolicy TakeEnergyCentroid
/gate/digitizer/Singles/readout/setDepth 1
/gate/digitizer/Coincidences/minSectorDifference 1
/gate/digitizer/Coincidences/setWindow 4.57 ns

/gate/source/addSource flash
/gate/source/flash/gps/particle gamma
/gate/source/flash/gps/ene/type Mono
/gate/source/flash/gps/ene/mono 511. keV
/gate/source/flash/setActivity 500000. becquerel
/gate/source/flash/gps/pos/centre 0. 0. 0. cm
/gate/source/flash/gps/ang/mintheta 90. deg
/gate/source/flash/gps/ang/maxtheta 90. deg
/gate/source/flash/gps/ang/minphi 180. deg
/gate/source/flash/gps/ang/maxphi 180. deg
/gate/source/flash/gps/direction 1 0 0
/gate/source/list


/gate/output/root/setFileName ../../calculTOF_outputs/GateOutputs/test1
/gate/output/root/setRootHitFlag 1
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setRootCoincidencesFlag 1
/gate/random/setEngineName MersenneTwister

/gate/application/setTimeSlice 1 s
/gate/application/setTimeStart 0. s
/gate/application/setTimeStop 1 s
/gate/random/setEngineSeed 1018557806058315992
/gate/output/root/enable
/gate/application/startDAQCluster 0 0.0625 0 s

