/gate/geometry/setMaterialDatabase GateMaterials.db
/gate/geometry/setMaterialDatabase ClMind_GateMaterials.db
/gate/world/geometry/setXLength 1000. mm
/gate/world/geometry/setYLength 1000. mm
/gate/world/geometry/setZLength 1000. mm
/gate/world/vis/setVisible 1
/gate/world/setMaterial Air
/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/geometry/setRmax 350. mm
/gate/cylindricalPET/geometry/setRmin 290. mm
/gate/cylindricalPET/geometry/setHeight 270. mm
/gate/cylindricalPET/placement/setTranslation 0.0 0.0 0.0 cm
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/daughters/name module
/gate/cylindricalPET/daughters/insert box
/gate/module/geometry/setXLength 64.5 mm
/gate/module/geometry/setYLength 25. mm
/gate/module/geometry/setZLength 250.4 mm
/gate/module/placement/setTranslation 0. 324.3 0. mm
/gate/module/setMaterial Air
/gate/module/vis/forceWireframe
/gate/module/vis/setColor white
/gate/module/daughters/name unit
/gate/module/daughters/insert box
/gate/unit/geometry/setXLength 64.5 mm
/gate/unit/geometry/setYLength 25. mm
/gate/unit/geometry/setZLength 47.84 mm
/gate/unit/placement/setTranslation 0. 0. 0. mm
/gate/unit/setMaterial Air
/gate/unit/vis/forceWireframe
/gate/unit/vis/setColor blue
/gate/unit/daughters/name block
/gate/unit/daughters/insert box
/gate/block/geometry/setXLength 15.9 mm
/gate/block/geometry/setYLength 25. mm
/gate/block/geometry/setZLength 47.84 mm
/gate/block/placement/setTranslation 0. 0. 0. mm
/gate/block/setMaterial Air
/gate/block/vis/forceWireframe
/gate/block/vis/setColor red
/gate/block/daughters/name optical
/gate/block/daughters/insert box
/gate/optical/geometry/setXLength 15.9 mm
/gate/optical/geometry/setYLength 25. mm
/gate/optical/geometry/setZLength 15.9 mm
/gate/optical/placement/setTranslation 0. 0. 0. mm
/gate/optical/setMaterial Air
/gate/optical/vis/forceWireframe
/gate/optical/vis/setColor yellow
/gate/optical/vis/setVisible 1
/gate/optical/daughters/name crystal
/gate/optical/daughters/insert box
/gate/crystal/geometry/setXLength 3.95 mm
/gate/crystal/geometry/setYLength 25. mm
/gate/crystal/geometry/setZLength 5.3 mm
/gate/crystal/placement/setTranslation 0. 0. 0. mm
/gate/crystal/setMaterial LYSO-GE
/gate/crystal/vis/forceWireframe
/gate/crystal/vis/setColor green
/gate/crystal/vis/setVisible 1
/gate/crystal/repeaters/insert cubicArray
/gate/crystal/cubicArray/setRepeatNumberX 4
/gate/crystal/cubicArray/setRepeatNumberY 1
/gate/crystal/cubicArray/setRepeatNumberZ 3
/gate/crystal/cubicArray/setRepeatVector 3.9833 0. 5.3 mm
/gate/optical/repeaters/insert linear
/gate/optical/linear/setRepeatNumber 3
/gate/optical/linear/setRepeatVector 0. 0. 15.97 mm
/gate/block/repeaters/insert linear
/gate/block/linear/setRepeatNumber 4
/gate/block/linear/setRepeatVector 16.20 0. 0. mm
/gate/unit/repeaters/insert linear
/gate/unit/linear/setRepeatNumber 5
/gate/unit/linear/setRepeatVector 0. 0. 50.64 mm
/gate/module/repeaters/insert ring
/gate/module/ring/setRepeatNumber 28
/gate/systems/cylindricalPET/rsector/attach module
/gate/systems/cylindricalPET/module/attach unit
/gate/systems/cylindricalPET/submodule/attach block
/gate/systems/cylindricalPET/crystal/attach optical
/gate/systems/cylindricalPET/layer0/attach crystal
/gate/crystal/attachCrystalSD
/gate/systems/cylindricalPET/describe

/gate/physics/addPhysicsList emstandard_opt3
/gate/physics/processList Enabled
/gate/physics/processList Initialized
/gate/physics/Gamma/SetCutInRegion world 1 mm
/gate/physics/Electron/SetCutInRegion world 1 mm
/gate/physics/displayCuts

/gate/world/daughters/name capillaire1
/gate/world/daughters/insert cylinder
/gate/capillaire1/geometry/setRmin 200. um
/gate/capillaire1/geometry/setRmax 700. um
/gate/capillaire1/geometry/setHeight 50. mm
/gate/capillaire1/placement/setTranslation 1. 0. 0. cm
/gate/capillaire1/setMaterial Glass
/gate/capillaire1/attachPhantomSD
/gate/world/daughters/name capillaire1_water
/gate/world/daughters/insert cylinder
/gate/capillaire1_water/geometry/setRmin 0. um
/gate/capillaire1_water/geometry/setRmax 200. um
/gate/capillaire1_water/geometry/setHeight 50. mm
/gate/capillaire1_water/setMaterial Water
/gate/capillaire1_water/placement/setTranslation 1. 0. 0. cm
/gate/capillaire1_water/attachPhantomSD
/gate/world/daughters/name capillaire2
/gate/world/daughters/insert cylinder
/gate/capillaire2/geometry/setRmin 200. um
/gate/capillaire2/geometry/setRmax 700. um
/gate/capillaire2/geometry/setHeight 50. mm
/gate/capillaire2/placement/setTranslation 5. 0. 0. cm
/gate/capillaire2/setMaterial Glass
/gate/capillaire2/attachPhantomSD
/gate/world/daughters/name capillaire2_water
/gate/world/daughters/insert cylinder
/gate/capillaire2_water/geometry/setRmin 0. um
/gate/capillaire2_water/geometry/setRmax 200. um
/gate/capillaire2_water/geometry/setHeight 50. mm
/gate/capillaire2_water/setMaterial Water
/gate/capillaire2_water/placement/setTranslation 5. 0. 0. cm
/gate/capillaire2_water/attachPhantomSD
/gate/world/daughters/name capillaire3
/gate/world/daughters/insert cylinder
/gate/capillaire3/geometry/setRmin 200. um
/gate/capillaire3/geometry/setRmax 700. um
/gate/capillaire3/geometry/setHeight 50. mm
/gate/capillaire3/placement/setTranslation 8. 0. 0. cm
/gate/capillaire3/setMaterial Glass
/gate/capillaire3/attachPhantomSD
/gate/world/daughters/name capillaire3_water
/gate/world/daughters/insert cylinder
/gate/capillaire3_water/geometry/setRmin 0. um
/gate/capillaire3_water/geometry/setRmax 200. um
/gate/capillaire3_water/geometry/setHeight 50. mm
/gate/capillaire3_water/setMaterial Water
/gate/capillaire3_water/placement/setTranslation 8. 0. 0. cm
/gate/capillaire3_water/attachPhantomSD
/gate/world/daughters/name capillaire4
/gate/world/daughters/insert cylinder
/gate/capillaire4/geometry/setRmin 200. um
/gate/capillaire4/geometry/setRmax 700. um
/gate/capillaire4/geometry/setHeight 50. mm
/gate/capillaire4/placement/setTranslation 11. 0. 0. cm
/gate/capillaire4/setMaterial Glass
/gate/capillaire4/attachPhantomSD
/gate/world/daughters/name capillaire4_water
/gate/world/daughters/insert cylinder
/gate/capillaire4_water/geometry/setRmin 0. um
/gate/capillaire4_water/geometry/setRmax 200. um
/gate/capillaire4_water/geometry/setHeight 50. mm
/gate/capillaire4_water/setMaterial Water
/gate/capillaire4_water/placement/setTranslation 11. 0. 0. cm
/gate/capillaire4_water/attachPhantomSD
/gate/world/daughters/name capillaire5
/gate/world/daughters/insert cylinder
/gate/capillaire5/geometry/setRmin 200. um
/gate/capillaire5/geometry/setRmax 700. um
/gate/capillaire5/geometry/setHeight 50. mm
/gate/capillaire5/placement/setTranslation 14. 0. 0. cm
/gate/capillaire5/setMaterial Glass
/gate/capillaire5/attachPhantomSD
/gate/world/daughters/name capillaire5_water
/gate/world/daughters/insert cylinder
/gate/capillaire5_water/geometry/setRmin 0. um
/gate/capillaire5_water/geometry/setRmax 200. um
/gate/capillaire5_water/geometry/setHeight 50. mm
/gate/capillaire5_water/setMaterial Water
/gate/capillaire5_water/placement/setTranslation 14. 0. 0. cm
/gate/capillaire5_water/attachPhantomSD
/gate/world/daughters/name capillaire_m1
/gate/world/daughters/insert cylinder
/gate/capillaire_m1/geometry/setRmin 200. um
/gate/capillaire_m1/geometry/setRmax 700. um
/gate/capillaire_m1/geometry/setHeight 50. mm
/gate/capillaire_m1/placement/setTranslation -5. 0. 0. cm
/gate/capillaire_m1/setMaterial Glass
/gate/capillaire_m1/attachPhantomSD
/gate/world/daughters/name capillaire_m1_water
/gate/world/daughters/insert cylinder
/gate/capillaire_m1_water/geometry/setRmin 0. um
/gate/capillaire_m1_water/geometry/setRmax 200. um
/gate/capillaire_m1_water/geometry/setHeight 50. mm
/gate/capillaire_m1_water/setMaterial Water
/gate/capillaire_m1_water/placement/setTranslation -5. 0. 0. cm
/gate/capillaire_m1_water/attachPhantomSD
/gate/world/daughters/name capillaire_m2
/gate/world/daughters/insert cylinder
/gate/capillaire_m2/geometry/setRmin 200. um
/gate/capillaire_m2/geometry/setRmax 700. um
/gate/capillaire_m2/geometry/setHeight 50. mm
/gate/capillaire_m2/placement/setTranslation -8. 0. 0. cm
/gate/capillaire_m2/setMaterial Glass
/gate/capillaire_m2/attachPhantomSD
/gate/world/daughters/name capillaire_m2_water
/gate/world/daughters/insert cylinder
/gate/capillaire_m2_water/geometry/setRmin 0. um
/gate/capillaire_m2_water/geometry/setRmax 200. um
/gate/capillaire_m2_water/geometry/setHeight 50. mm
/gate/capillaire_m2_water/setMaterial Water
/gate/capillaire_m2_water/placement/setTranslation -8. 0. 0. cm
/gate/capillaire_m2_water/attachPhantomSD
/gate/world/daughters/name capillaire_m3
/gate/world/daughters/insert cylinder
/gate/capillaire_m3/geometry/setRmin 200. um
/gate/capillaire_m3/geometry/setRmax 700. um
/gate/capillaire_m3/geometry/setHeight 50. mm
/gate/capillaire_m3/placement/setTranslation -11. 0. 0. cm
/gate/capillaire_m3/setMaterial Glass
/gate/capillaire_m3/attachPhantomSD
/gate/world/daughters/name capillaire_m3_water
/gate/world/daughters/insert cylinder
/gate/capillaire_m3_water/geometry/setRmin 0. um
/gate/capillaire_m3_water/geometry/setRmax 200. um
/gate/capillaire_m3_water/geometry/setHeight 50. mm
/gate/capillaire_m3_water/setMaterial Water
/gate/capillaire_m3_water/placement/setTranslation -11. 0. 0. cm
/gate/capillaire_m3_water/attachPhantomSD
/gate/world/daughters/name capillaire_m4
/gate/world/daughters/insert cylinder
/gate/capillaire_m4/geometry/setRmin 200. um
/gate/capillaire_m4/geometry/setRmax 700. um
/gate/capillaire_m4/geometry/setHeight 50. mm
/gate/capillaire_m4/placement/setTranslation -14. 0. 0. cm
/gate/capillaire_m4/setMaterial Glass
/gate/capillaire_m4/attachPhantomSD
/gate/world/daughters/name capillaire_m4_water
/gate/world/daughters/insert cylinder
/gate/capillaire_m4_water/geometry/setRmin 0. um
/gate/capillaire_m4_water/geometry/setRmax 200. um
/gate/capillaire_m4_water/geometry/setHeight 50. mm
/gate/capillaire_m4_water/setMaterial Water
/gate/capillaire_m4_water/placement/setTranslation -14. 0. 0. cm
/gate/capillaire_m4_water/attachPhantomSD

/gate/run/initialize
/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/adder/positionPolicy energyWeightedCentroid
/gate/digitizer/Singles/insert spblurring
/gate/digitizer/Singles/spblurring/setSpresolution 1.0 mm
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setPolicy TakeEnergyWinner
/gate/digitizer/Singles/readout/setDepth 1
/gate/digitizer/Coincidences/setWindow 4.57 ns

/gate/source/addSource hof voxel
/gate/source/hof/reader/insert image
/gate/source/hof/imageReader/translator/insert range
/gate/source/hof/imageReader/rangeTranslator/readTable act_range_vox_modFois3.dat
/gate/source/hof/imageReader/rangeTranslator/describe 1
/gate/source/hof/imageReader/readFile ../fantomes/hof3.h33
/gate/source/hof/imageReader/verbose 1
/gate/source/hof/setPosition -128. -128. -55. mm
/gate/source/hof/dump 1
/gate/source/hof/setType backtoback
/gate/source/hof/gps/particle gamma
/gate/source/hof/gps/energytype Mono
/gate/source/hof/gps/monoenergy 511. keV
/gate/source/hof/gps/angtype iso
/gate/source/hof/gps/mintheta 0. deg
/gate/source/hof/gps/maxtheta 90. deg
/gate/source/hof/gps/minphi 0. deg
/gate/source/hof/gps/maxphi 360. deg
/gate/source/hof/gps/confine NULL

/vis/disable

/gate/output/root/setFileName ../../calculTOF_outputs/GateOutputs/spblurringTest_1mm2
/gate/output/root/setRootHitFlag 1
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setRootCoincidencesFlag 1
/gate/random/setEngineName MersenneTwister

/gate/application/setTimeSlice 0.00001 s
/gate/application/setTimeStart 0. s
/gate/application/setTimeStop 0.00001 s
/gate/random/setEngineSeed 330738892368319659
/gate/output/root/enable
/gate/application/startDAQCluster 6.25e-07 1.25e-06 0 s

