/gate/source/addSource                        mySource

/gate/source/mySource/gps/particle gamma
/gate/source/mySource/setType backtoback
/gate/source/mySource/gps/ene/type  Mono
/gate/source/mySource/gps/ene/mono 511. keV


/gate/source/mySource/setActivity                 100000. becquerel
/gate/source/mySource/gps/type Volume
/gate/source/mySource/gps/angtype iso
/gate/source/mySource/gps/shape Cylinder
/gate/source/mySource/gps/radius 10. mm
/gate/source/mySource/gps/halfz 10. mm
/gate/source/mySource/gps/pos/centre                  0. 0. 0. mm


/gate/source/addSource                        mySource2

/gate/source/mySource2/gps/particle gamma
/gate/source/mySource2/setType backtoback
/gate/source/mySource2/gps/ene/type  Mono
/gate/source/mySource2/gps/ene/mono 511. keV


/gate/source/mySource2/setActivity                 100000. becquerel
/gate/source/mySource2/gps/type Volume
/gate/source/mySource2/gps/angtype iso
/gate/source/mySource2/gps/shape Sphere
/gate/source/mySource2/gps/radius 5. mm
/gate/source/mySource2/gps/pos/centre                  50. 0. 0. mm


/gate/source/addSource                        mySource3

/gate/source/mySource3/gps/particle gamma
/gate/source/mySource3/setType backtoback
/gate/source/mySource3/gps/ene/type  Mono
/gate/source/mySource3/gps/ene/mono 511. keV


/gate/source/mySource3/setActivity                 100000. becquerel
/gate/source/mySource3/gps/type Volume
/gate/source/mySource3/gps/angtype iso
/gate/source/mySource3/gps/shape Sphere
/gate/source/mySource3/gps/radius 5. mm
/gate/source/mySource3/gps/pos/centre                  61. 0. 0. mm

/gate/source/addSource                        mySource4

/gate/source/mySource4/gps/particle gamma
/gate/source/mySource4/setType backtoback
/gate/source/mySource4/gps/ene/type  Mono
/gate/source/mySource4/gps/ene/mono 511. keV


/gate/source/mySource4/setActivity                 500000. becquerel
/gate/source/mySource4/gps/type Volume
/gate/source/mySource4/gps/angtype iso
/gate/source/mySource4/gps/shape Sphere
/gate/source/mySource4/gps/radius 2. mm
/gate/source/mySource4/gps/pos/centre                  0. 0. 0. mm
