#-----------------------------------------------------
#	PHYSICS
#=====================================================
/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel
/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel
/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel
/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+
/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+
/gate/physics/addProcess PositronAnnihilation
/gate/physics/addProcess eMultipleScattering e+
/gate/physics/addProcess eMultipleScattering e-

/gate/physics/addProcess    Cerenkov 
/gate/physics/addProcess    Scintillation 
/gate/physics/addProcess    OpticalAbsorption 
/gate/physics/addProcess    OpticalRayleigh 
/gate/physics/addProcess    OpticalBoundary 
/gate/physics/addProcess    OpticalMie 
/gate/physics/addProcess    OpticalWLS 
/gate/physics/processList   Enabled 
/gate/physics/processList Initialized



#-----------------------------------------------------
#	CUTS
#=====================================================

#/gate/physics/Electron/SetCutInRegion   PbWO4_crystal 0.1 nm

#/gate/physics/Electron/SetCutInRegion   PhotElec_Layer 0.1 nm

#/gate/physics/Electron/SetCutInRegion   Coating_Layer 0.1 nm

