/gate/geometry/setMaterialDatabase GateMaterials.db
/gate/geometry/setMaterialDatabase ClMind_GateMaterials.db
/gate/world/geometry/setXLength 1000. mm
/gate/world/geometry/setYLength 1000. mm
/gate/world/geometry/setZLength 1000. mm
/gate/world/vis/setVisible 1
/gate/world/setMaterial Air
/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/geometry/setRmax 350. mm
/gate/cylindricalPET/geometry/setRmin 290. mm
/gate/cylindricalPET/geometry/setHeight 270. mm
/gate/cylindricalPET/placement/setTranslation 0.0 0.0 0.0 cm
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/daughters/name module
/gate/cylindricalPET/daughters/insert box
/gate/module/geometry/setXLength 64.5 mm
/gate/module/geometry/setYLength 25. mm
/gate/module/geometry/setZLength 250.4 mm
/gate/module/placement/setTranslation 0. 324.3 0. mm
/gate/module/setMaterial Air
/gate/module/vis/forceWireframe
/gate/module/vis/setColor white
/gate/module/daughters/name unit
/gate/module/daughters/insert box
/gate/unit/geometry/setXLength 64.5 mm
/gate/unit/geometry/setYLength 25. mm
/gate/unit/geometry/setZLength 47.84 mm
/gate/unit/placement/setTranslation 0. 0. 0. mm
/gate/unit/setMaterial Air
/gate/unit/vis/forceWireframe
/gate/unit/vis/setColor blue
/gate/unit/daughters/name block
/gate/unit/daughters/insert box
/gate/block/geometry/setXLength 15.9 mm
/gate/block/geometry/setYLength 25. mm
/gate/block/geometry/setZLength 47.84 mm
/gate/block/placement/setTranslation 0. 0. 0. mm
/gate/block/setMaterial Air
/gate/block/vis/forceWireframe
/gate/block/vis/setColor red
/gate/block/daughters/name optical
/gate/block/daughters/insert box
/gate/optical/geometry/setXLength 15.9 mm
/gate/optical/geometry/setYLength 25. mm
/gate/optical/geometry/setZLength 15.9 mm
/gate/optical/placement/setTranslation 0. 0. 0. mm
/gate/optical/setMaterial Air
/gate/optical/vis/forceWireframe
/gate/optical/vis/setColor yellow
/gate/optical/vis/setVisible 1
/gate/optical/daughters/name crystal
/gate/optical/daughters/insert box
/gate/crystal/geometry/setXLength 3.95 mm
/gate/crystal/geometry/setYLength 25. mm
/gate/crystal/geometry/setZLength 5.3 mm
/gate/crystal/placement/setTranslation 0. 0. 0. mm
/gate/crystal/setMaterial LYSO-GE
/gate/crystal/vis/forceWireframe
/gate/crystal/vis/setColor green
/gate/crystal/vis/setVisible 1
/gate/crystal/repeaters/insert cubicArray
/gate/crystal/cubicArray/setRepeatNumberX 4
/gate/crystal/cubicArray/setRepeatNumberY 1
/gate/crystal/cubicArray/setRepeatNumberZ 3
/gate/crystal/cubicArray/setRepeatVector 3.9833 0. 5.3 mm
/gate/optical/repeaters/insert linear
/gate/optical/linear/setRepeatNumber 3
/gate/optical/linear/setRepeatVector 0. 0. 15.97 mm
/gate/block/repeaters/insert linear
/gate/block/linear/setRepeatNumber 4
/gate/block/linear/setRepeatVector 16.20 0. 0. mm
/gate/unit/repeaters/insert linear
/gate/unit/linear/setRepeatNumber 5
/gate/unit/linear/setRepeatVector 0. 0. 50.64 mm
/gate/module/repeaters/insert ring
/gate/module/ring/setRepeatNumber 28
/gate/systems/cylindricalPET/rsector/attach module
/gate/systems/cylindricalPET/module/attach unit
/gate/systems/cylindricalPET/submodule/attach block
/gate/systems/cylindricalPET/crystal/attach optical
/gate/systems/cylindricalPET/layer0/attach crystal
/gate/crystal/attachCrystalSD
/gate/systems/cylindricalPET/describe

/gate/physics/addPhysicsList emstandard_opt3
/gate/physics/processList Enabled
/gate/physics/processList Initialized
/gate/physics/Gamma/SetCutInRegion world 1 mm
/gate/physics/Electron/SetCutInRegion world 1 mm
/gate/physics/displayCuts

/gate/run/initialize
/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/adder/positionPolicy energyWeightedCentroid
/gate/digitizer/Singles/insert spblurring
/gate/digitizer/Singles/spblurring/setSpresolution 1.0 mm
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setPolicy TakeEnergyWinner
/gate/digitizer/Singles/readout/setDepth 1
/gate/digitizer/Coincidences/setWindow 4.57 ns

/gate/source/addSource upperinterior_hot
/gate/source/upperinterior_hot/gps/centre 0.0 -3.5 0.0 cm
/gate/source/upperinterior_hot/gps/type Volume
/gate/source/upperinterior_hot/gps/shape Cylinder
/gate/source/upperinterior_hot/gps/radius 14.7 cm
/gate/source/upperinterior_hot/gps/halfz 10.7 cm
/gate/source/upperinterior_hot/setActivity 36028186 Bq
/gate/source/upperinterior_hot/setType backtoback
/gate/source/upperinterior_hot/gps/particle gamma
/gate/source/upperinterior_hot/gps/ene/mono 511. keV
/gate/source/upperinterior_hot/gps/angtype iso
/gate/source/upperinterior_hot/gps/Forbid NEMA_IQ
/gate/source/upperinterior_hot/gps/Forbid NEMA_IQ_cold
/gate/source/upperinterior_hot/gps/Forbid centercyl
/gate/source/upperinterior_hot/gps/Forbid centercylin
/gate/source/upperinterior_hot/gps/Forbid sphere10
/gate/source/upperinterior_hot/gps/Forbid sphere10in
/gate/source/upperinterior_hot/gps/Forbid fill10
/gate/source/upperinterior_hot/gps/Forbid fill10in
/gate/source/upperinterior_hot/gps/Forbid sphere13
/gate/source/upperinterior_hot/gps/Forbid sphere13in
/gate/source/upperinterior_hot/gps/Forbid fill13
/gate/source/upperinterior_hot/gps/Forbid fill13in
/gate/source/upperinterior_hot/gps/Forbid sphere17
/gate/source/upperinterior_hot/gps/Forbid sphere17in
/gate/source/upperinterior_hot/gps/Forbid fill17
/gate/source/upperinterior_hot/gps/Forbid fill17in
/gate/source/upperinterior_hot/gps/Forbid sphere37
/gate/source/upperinterior_hot/gps/Forbid sphere37in
/gate/source/upperinterior_hot/gps/Forbid fill37
/gate/source/upperinterior_hot/gps/Forbid fill37in
/gate/source/upperinterior_hot/gps/Forbid sphere22
/gate/source/upperinterior_hot/gps/Forbid sphere22in
/gate/source/upperinterior_hot/gps/Forbid fill22
/gate/source/upperinterior_hot/gps/Forbid fill22in
/gate/source/upperinterior_hot/gps/Forbid sphere28
/gate/source/upperinterior_hot/gps/Forbid sphere28in
/gate/source/upperinterior_hot/gps/Forbid fill28
/gate/source/upperinterior_hot/gps/Forbid fill28in
/gate/source/upperinterior_hot/gps/Forbid boxinterior
/gate/source/upperinterior_hot/gps/Forbid LLinterior
/gate/source/upperinterior_hot/gps/Forbid LRinterior
/gate/source/upperinterior_hot/gps/Forbid outershell1
/gate/source/upperinterior_hot/gps/Forbid outershell2
/gate/source/upperinterior_hot/gps/Forbid outershell3
/gate/source/upperinterior_hot/gps/Forbid outershell4
/gate/source/upperinterior_hot/dump 35
/gate/source/addSource LRinterior_hot
/gate/source/LRinterior_hot/gps/centre -7.0 -3.5 0.0 cm
/gate/source/LRinterior_hot/gps/type Volume
/gate/source/LRinterior_hot/gps/shape Cylinder
/gate/source/LRinterior_hot/gps/radius 7.7 cm
/gate/source/LRinterior_hot/gps/halfz 10.7 cm
/gate/source/LRinterior_hot/setActivity 5281545 Bq
/gate/source/LRinterior_hot/setType backtoback
/gate/source/LRinterior_hot/gps/particle gamma
/gate/source/LRinterior_hot/gps/ene/mono 511. keV
/gate/source/LRinterior_hot/gps/angtype iso
/gate/source/LRinterior_hot/gps/Forbid upperinterior
/gate/source/LRinterior_hot/gps/Forbid boxinterior
/gate/source/LRinterior_hot/gps/Forbid centercyl
/gate/source/LRinterior_hot/gps/Forbid centercylin
/gate/source/LRinterior_hot/gps/Forbid sphere17
/gate/source/LRinterior_hot/gps/Forbid sphere17in
/gate/source/LRinterior_hot/gps/Forbid fill17
/gate/source/LRinterior_hot/gps/Forbid fill17in
/gate/source/LRinterior_hot/gps/Forbid sphere22
/gate/source/LRinterior_hot/gps/Forbid sphere22in
/gate/source/LRinterior_hot/gps/Forbid fill22
/gate/source/LRinterior_hot/gps/Forbid fill22in
/gate/source/LRinterior_hot/dump 12
/gate/source/addSource LLinterior_hot
/gate/source/LLinterior_hot/gps/centre 7.0 -3.5 0.0 cm
/gate/source/LLinterior_hot/gps/type Volume
/gate/source/LLinterior_hot/gps/shape Cylinder
/gate/source/LLinterior_hot/gps/radius 7.7 cm
/gate/source/LLinterior_hot/gps/halfz 10.7 cm
/gate/source/LLinterior_hot/setActivity 5281545 Bq
/gate/source/LLinterior_hot/setType backtoback
/gate/source/LLinterior_hot/gps/particle gamma
/gate/source/LLinterior_hot/gps/ene/mono 511. keV
/gate/source/LLinterior_hot/gps/angtype iso
/gate/source/LLinterior_hot/gps/Forbid upperinterior
/gate/source/LLinterior_hot/gps/Forbid boxinterior
/gate/source/LLinterior_hot/gps/Forbid centercyl
/gate/source/LLinterior_hot/gps/Forbid centercylin
/gate/source/LLinterior_hot/gps/Forbid sphere28
/gate/source/LLinterior_hot/gps/Forbid sphere28in
/gate/source/LLinterior_hot/gps/Forbid fill28
/gate/source/LLinterior_hot/gps/Forbid fill28in
/gate/source/LLinterior_hot/gps/Forbid sphere37
/gate/source/LLinterior_hot/gps/Forbid sphere37in
/gate/source/LLinterior_hot/gps/Forbid fill37
/gate/source/LLinterior_hot/gps/Forbid fill37in
/gate/source/LLinterior_hot/dump 12
/gate/source/addSource interiorbox_hot
/gate/source/interiorbox_hot/gps/centre 0.0 -7.35. 0.0 cm
/gate/source/interiorbox_hot/gps/type Volume
/gate/source/interiorbox_hot/gps/shape Para
/gate/source/interiorbox_hot/gps/halfx 7. cm
/gate/source/interiorbox_hot/gps/halfy 3.85 cm
/gate/source/interiorbox_hot/gps/halfz 10.7 cm
/gate/source/interiorbox_hot/setActivity 12090338 Bq
/gate/source/interiorbox_hot/setType backtoback
/gate/source/interiorbox_hot/gps/particle gamma
/gate/source/interiorbox_hot/gps/ene/mono 511. keV
/gate/source/interiorbox_hot/gps/angtype iso
/gate/source/interiorbox_hot/gps/Forbid sphere22
/gate/source/interiorbox_hot/gps/Forbid sphere22in
/gate/source/interiorbox_hot/gps/Forbid fill22
/gate/source/interiorbox_hot/gps/Forbid fill22in
/gate/source/interiorbox_hot/gps/Forbid sphere28
/gate/source/interiorbox_hot/gps/Forbid sphere28in
/gate/source/interiorbox_hot/gps/Forbid fill28
/gate/source/interiorbox_hot/gps/Forbid fill28in
/gate/source/interiorbox_hot/dump 8
/gate/source/addSource sphere10mm gps
/gate/source/sphere10mm/gps/centre 2.86 4.95367 3.7 cm
/gate/source/sphere10mm/gps/type Volume
/gate/source/sphere10mm/gps/shape Sphere
/gate/source/sphere10mm/gps/radius 0.5 cm
/gate/source/sphere10mm/setActivity 11100. Bq
/gate/source/sphere10mm/setType backtoback
/gate/source/sphere10mm/gps/particle gamma
/gate/source/sphere10mm/gps/ene/mono 511. keV
/gate/source/sphere10mm/gps/angtype iso
/gate/source/addSource capillary10mm gps
/gate/source/capillary10mm/gps/centre 2.86 4.95367 7.5 cm
/gate/source/capillary10mm/gps/type Volume
/gate/source/capillary10mm/gps/shape Cylinder
/gate/source/capillary10mm/gps/radius 0.25 cm
/gate/source/capillary10mm/gps/halfz 3.2 cm
/gate/source/capillary10mm/setActivity 26641. Bq
/gate/source/capillary10mm/setType backtoback
/gate/source/capillary10mm/gps/particle gamma
/gate/source/capillary10mm/gps/ene/mono 511. keV
/gate/source/capillary10mm/gps/angtype iso
/gate/source/addSource sphere13mm gps
/gate/source/sphere13mm/gps/centre -2.86 4.95367 3.7 cm
/gate/source/sphere13mm/gps/type Volume
/gate/source/sphere13mm/gps/shape Sphere
/gate/source/sphere13mm/gps/radius 0.65 cm
/gate/source/sphere13mm/setActivity 24387. Bq
/gate/source/sphere13mm/setType backtoback
/gate/source/sphere13mm/gps/particle gamma
/gate/source/sphere13mm/gps/ene/mono 511. keV
/gate/source/sphere13mm/gps/angtype iso
/gate/source/addSource capillary13mm gps
/gate/source/capillary13mm/gps/centre -2.86 4.95367 7.5875 cm
/gate/source/capillary13mm/gps/type Volume
/gate/source/capillary13mm/gps/shape Cylinder
/gate/source/capillary13mm/gps/radius 0.25 cm
/gate/source/capillary13mm/gps/halfz 3.1125 cm
/gate/source/capillary13mm/setActivity 25912. Bq
/gate/source/capillary13mm/setType backtoback
/gate/source/capillary13mm/gps/particle gamma
/gate/source/capillary13mm/gps/ene/mono 511. keV
/gate/source/capillary13mm/gps/angtype iso
/gate/source/addSource sphere17mm gps
/gate/source/sphere17mm/gps/centre -5.72 0. 3.7 cm
/gate/source/sphere17mm/gps/type Volume
/gate/source/sphere17mm/gps/shape Sphere
/gate/source/sphere17mm/gps/radius 0.85 cm
/gate/source/sphere17mm/setActivity 54536. Bq
/gate/source/sphere17mm/setType backtoback
/gate/source/sphere17mm/gps/particle gamma
/gate/source/sphere17mm/gps/ene/mono 511. keV
/gate/source/sphere17mm/gps/angtype iso
/gate/source/addSource capillary17mm gps
/gate/source/capillary17mm/gps/centre -5.72 0. 7.675 cm
/gate/source/capillary17mm/gps/type Volume
/gate/source/capillary17mm/gps/shape Cylinder
/gate/source/capillary17mm/gps/radius 0.25 cm
/gate/source/capillary17mm/gps/halfz 3.025 cm
/gate/source/capillary17mm/setActivity 25184. Bq
/gate/source/capillary17mm/setType backtoback
/gate/source/capillary17mm/gps/particle gamma
/gate/source/capillary17mm/gps/ene/mono 511. keV
/gate/source/capillary17mm/gps/angtype iso
/gate/source/addSource sphere22mm gps
/gate/source/sphere22mm/gps/centre -2.86 -4.95367 3.7 cm
/gate/source/sphere22mm/gps/type Volume
/gate/source/sphere22mm/gps/shape Sphere
/gate/source/sphere22mm/gps/radius 1.1 cm
/gate/source/sphere22mm/setActivity 118196. Bq
/gate/source/sphere22mm/setType backtoback
/gate/source/sphere22mm/gps/particle gamma
/gate/source/sphere22mm/gps/ene/mono 511. keV
/gate/source/sphere22mm/gps/angtype iso
/gate/source/addSource capillary22mm gps
/gate/source/capillary22mm/gps/centre -2.86 -4.95367 7.8 cm
/gate/source/capillary22mm/gps/type Volume
/gate/source/capillary22mm/gps/shape Cylinder
/gate/source/capillary22mm/gps/radius 0.25 cm
/gate/source/capillary22mm/gps/halfz 2.9 cm
/gate/source/capillary22mm/setActivity 24143. Bq
/gate/source/capillary22mm/setType backtoback
/gate/source/capillary22mm/gps/particle gamma
/gate/source/capillary22mm/gps/ene/mono 511. keV
/gate/source/capillary22mm/gps/angtype iso
/gate/source/list

/vis/disable

/gate/output/root/setFileName ../../calculTOF_outputs/GateOutputs/NEMA_IQ10
/gate/output/root/setRootHitFlag 1
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setRootCoincidencesFlag 1
/gate/random/setEngineName MersenneTwister

/gate/application/setTimeSlice 1 s
/gate/application/setTimeStart 0. s
/gate/application/setTimeStop 1 s
/gate/random/setEngineSeed 906519664630500592
/gate/output/root/enable
/gate/application/startDAQCluster 0.9 1 0 s

