/gate/geometry/setMaterialDatabase GateMaterials.db
/gate/geometry/setMaterialDatabase ClMind_GateMaterials.db
/gate/world/geometry/setXLength 1000. mm
/gate/world/geometry/setYLength 1000. mm
/gate/world/geometry/setZLength 1000. mm
/gate/world/vis/setVisible 1
/gate/world/setMaterial Air
/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/geometry/setRmax 350. mm
/gate/cylindricalPET/geometry/setRmin 290. mm
/gate/cylindricalPET/geometry/setHeight 270. mm
/gate/cylindricalPET/placement/setTranslation 0.0 0.0 0.0 cm
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/daughters/name module
/gate/cylindricalPET/daughters/insert box
/gate/module/geometry/setXLength 64.5 mm
/gate/module/geometry/setYLength 25. mm
/gate/module/geometry/setZLength 250.4 mm
/gate/module/placement/setTranslation 0. 324.3 0. mm
/gate/module/setMaterial Air
/gate/module/vis/forceWireframe
/gate/module/vis/setColor white
/gate/module/daughters/name unit
/gate/module/daughters/insert box
/gate/unit/geometry/setXLength 64.5 mm
/gate/unit/geometry/setYLength 25. mm
/gate/unit/geometry/setZLength 47.84 mm
/gate/unit/placement/setTranslation 0. 0. 0. mm
/gate/unit/setMaterial Air
/gate/unit/vis/forceWireframe
/gate/unit/vis/setColor blue
/gate/unit/daughters/name block
/gate/unit/daughters/insert box
/gate/block/geometry/setXLength 15.9 mm
/gate/block/geometry/setYLength 25. mm
/gate/block/geometry/setZLength 47.84 mm
/gate/block/placement/setTranslation 0. 0. 0. mm
/gate/block/setMaterial Air
/gate/block/vis/forceWireframe
/gate/block/vis/setColor red
/gate/block/daughters/name optical
/gate/block/daughters/insert box
/gate/optical/geometry/setXLength 15.9 mm
/gate/optical/geometry/setYLength 25. mm
/gate/optical/geometry/setZLength 15.9 mm
/gate/optical/placement/setTranslation 0. 0. 0. mm
/gate/optical/setMaterial Air
/gate/optical/vis/forceWireframe
/gate/optical/vis/setColor yellow
/gate/optical/vis/setVisible 1
/gate/optical/daughters/name crystal
/gate/optical/daughters/insert box
/gate/crystal/geometry/setXLength 3.95 mm
/gate/crystal/geometry/setYLength 25. mm
/gate/crystal/geometry/setZLength 5.3 mm
/gate/crystal/placement/setTranslation 0. 0. 0. mm
/gate/crystal/setMaterial LYSO-GE
/gate/crystal/vis/forceWireframe
/gate/crystal/vis/setColor green
/gate/crystal/vis/setVisible 1
/gate/crystal/repeaters/insert cubicArray
/gate/crystal/cubicArray/setRepeatNumberX 4
/gate/crystal/cubicArray/setRepeatNumberY 1
/gate/crystal/cubicArray/setRepeatNumberZ 3
/gate/crystal/cubicArray/setRepeatVector 3.9833 0. 5.3 mm
/gate/optical/repeaters/insert linear
/gate/optical/linear/setRepeatNumber 3
/gate/optical/linear/setRepeatVector 0. 0. 15.97 mm
/gate/block/repeaters/insert linear
/gate/block/linear/setRepeatNumber 4
/gate/block/linear/setRepeatVector 16.20 0. 0. mm
/gate/unit/repeaters/insert linear
/gate/unit/linear/setRepeatNumber 5
/gate/unit/linear/setRepeatVector 0. 0. 50.64 mm
/gate/module/repeaters/insert ring
/gate/module/ring/setRepeatNumber 28
/gate/systems/cylindricalPET/rsector/attach module
/gate/systems/cylindricalPET/module/attach unit
/gate/systems/cylindricalPET/submodule/attach block
/gate/systems/cylindricalPET/crystal/attach optical
/gate/systems/cylindricalPET/layer0/attach crystal
/gate/crystal/attachCrystalSD
/gate/systems/cylindricalPET/describe

/gate/physics/addPhysicsList emstandard_opt3
/gate/physics/processList Enabled
/gate/physics/processList Initialized
/gate/physics/Gamma/SetCutInRegion world 1 mm
/gate/physics/Electron/SetCutInRegion world 1 mm
/gate/physics/displayCuts


/gate/world/daughters/name body_cylinder
/gate/world/daughters/insert cylinder
/gate/body_cylinder/geometry/setRmin 0. mm
/gate/body_cylinder/geometry/setRmax 100. mm
/gate/body_cylinder/geometry/setHeight 180. mm
/gate/body_cylinder/placement/setTranslation 0. 0. 0. mm
/gate/body_cylinder/setMaterial PMMA
/gate/body_cylinder/attachPhantomSD
/gate/body_cylinder/vis/forceSolid
/gate/body_cylinder/vis/setColor white
/gate/body_cylinder/daughters/name body_water
/gate/body_cylinder/daughters/insert cylinder
/gate/body_water/geometry/setRmin 0. mm
/gate/body_water/geometry/setRmax 93. mm
/gate/body_water/geometry/setHeight 180. mm
/gate/body_water/setMaterial Water
/gate/body_water/attachPhantomSD
/gate/body_water/vis/setVisible 0
/gate/body_cylinder/daughters/name ball1
/gate/body_cylinder/daughters/insert sphere
/gate/ball1/geometry/setRmin 0. mm
/gate/ball1/geometry/setRmax 5.9 mm
/gate/ball1/placement/setTranslation 28.6 49.54 75. mm
/gate/ball1/setMaterial Glass
/gate/ball1/attachPhantomSD
/gate/ball1/vis/setVisible 1
/gate/ball1/vis/forceSolid
/gate/ball1/vis/setColor red
/gate/ball1/daughters/name water_ball1
/gate/ball1/daughters/insert sphere
/gate/water_ball1/geometry/setRmin 0. mm
/gate/water_ball1/geometry/setRmax 5. mm
/gate/water_ball1/setMaterial Water
/gate/water_ball1/attachPhantomSD
/gate/water_ball1/vis/setVisible 0
/gate/body_cylinder/daughters/name ball2
/gate/body_cylinder/daughters/insert sphere
/gate/ball2/geometry/setRmin 0. mm
/gate/ball2/geometry/setRmax 7.4 mm
/gate/ball2/placement/setTranslation -28.6 49.54 75. mm
/gate/ball2/setMaterial Glass
/gate/ball2/attachPhantomSD
/gate/ball2/vis/setVisible 1
/gate/ball2/vis/forceSolid
/gate/ball2/vis/setColor red
/gate/ball2/daughters/name water_ball2
/gate/ball2/daughters/insert sphere
/gate/water_ball2/geometry/setRmin 0. mm
/gate/water_ball2/geometry/setRmax 6.5 mm
/gate/water_ball2/setMaterial Water
/gate/water_ball2/attachPhantomSD
/gate/water_ball2/vis/setVisible 0
/gate/body_cylinder/daughters/name ball3
/gate/body_cylinder/daughters/insert sphere
/gate/ball3/geometry/setRmin 0. mm
/gate/ball3/geometry/setRmax 9.4 mm
/gate/ball3/placement/setTranslation -57.2 0. 75. mm
/gate/ball3/setMaterial Glass
/gate/ball3/attachPhantomSD
/gate/ball3/vis/setVisible 1
/gate/ball3/vis/forceSolid
/gate/ball3/vis/setColor red
/gate/ball3/daughters/name water_ball3
/gate/ball3/daughters/insert sphere
/gate/water_ball3/geometry/setRmin 0. mm
/gate/water_ball3/geometry/setRmax 8.5 mm
/gate/water_ball3/setMaterial Water
/gate/water_ball3/attachPhantomSD
/gate/water_ball3/vis/setVisible 0
/gate/body_cylinder/daughters/name ball4
/gate/body_cylinder/daughters/insert sphere
/gate/ball4/geometry/setRmin 0. mm
/gate/ball4/geometry/setRmax 11.9 mm
/gate/ball4/placement/setTranslation -28.6 -49.54 75. mm
/gate/ball4/setMaterial Glass
/gate/ball4/attachPhantomSD
/gate/ball4/vis/setVisible 1
/gate/ball4/vis/forceSolid
/gate/ball4/vis/setColor red
/gate/ball4/daughters/name water_ball4
/gate/ball4/daughters/insert sphere
/gate/water_ball4/geometry/setRmin 0. mm
/gate/water_ball4/geometry/setRmax 11. mm
/gate/water_ball4/setMaterial Water
/gate/water_ball4/attachPhantomSD
/gate/water_ball4/vis/setVisible 0
/gate/body_cylinder/daughters/name ball5
/gate/body_cylinder/daughters/insert sphere
/gate/ball5/geometry/setRmin 0. mm
/gate/ball5/geometry/setRmax 14.9 mm
/gate/ball5/placement/setTranslation 28.6 -49.54 75. mm
/gate/ball5/setMaterial Glass
/gate/ball5/attachPhantomSD
/gate/ball5/vis/setVisible 1
/gate/ball5/vis/forceSolid
/gate/ball5/vis/setColor green
/gate/ball5/daughters/name water_ball5
/gate/ball5/daughters/insert sphere
/gate/water_ball5/geometry/setRmin 0. mm
/gate/water_ball5/geometry/setRmax 14. mm
/gate/water_ball5/setMaterial Water
/gate/water_ball5/attachPhantomSD
/gate/water_ball5/vis/setVisible 0
/gate/body_cylinder/daughters/name ball6
/gate/body_cylinder/daughters/insert sphere
/gate/ball6/geometry/setRmin 0. mm
/gate/ball6/geometry/setRmax 19.4 mm
/gate/ball6/placement/setTranslation 57.2 0. 75. mm
/gate/ball6/setMaterial Glass
/gate/ball6/attachPhantomSD
/gate/ball6/vis/setVisible 1
/gate/ball6/vis/forceSolid
/gate/ball6/vis/setColor green
/gate/ball6/daughters/name water_ball6
/gate/ball6/daughters/insert sphere
/gate/water_ball6/geometry/setRmin 0. mm
/gate/water_ball6/geometry/setRmax 18.5 mm
/gate/water_ball6/setMaterial Water
/gate/water_ball6/attachPhantomSD
/gate/water_ball6/vis/setVisible 0

/gate/run/initialize
/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/adder/positionPolicy energyWeightedCentroid
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setPolicy TakeEnergyWinner
/gate/digitizer/Singles/readout/setDepth 1
/gate/digitizer/Coincidences/setWindow 4.57 ns

/gate/source/addSource sourceBodyWater
/gate/source/sourceBodyWater/gps/particle gamma
/gate/source/sourceBodyWater/setType backtoback
/gate/source/sourceBodyWater/gps/ene/type Mono
/gate/source/sourceBodyWater/gps/ene/mono 511. keV
/gate/source/sourceBodyWater/setActivity 40000000. becquerel
/gate/source/sourceBodyWater/gps/type Volume
/gate/source/sourceBodyWater/gps/angtype iso
/gate/source/sourceBodyWater/gps/shape Cylinder
/gate/source/sourceBodyWater/gps/radius 93. mm
/gate/source/sourceBodyWater/gps/halfz 180. mm
/gate/source/sourceBodyWater/gps/pos/centre 0. 0. 0. mm
/gate/source/addSource sourceBall1
/gate/source/sourceBall1/gps/particle gamma
/gate/source/sourceBall1/setType backtoback
/gate/source/sourceBall1/gps/ene/type Mono
/gate/source/sourceBall1/gps/ene/mono 511. keV
/gate/source/sourceBall1/setActivity 12880. becquerel
/gate/source/sourceBall1/gps/type Volume
/gate/source/sourceBall1/gps/angtype iso
/gate/source/sourceBall1/gps/shape Sphere
/gate/source/sourceBall1/gps/radius 5. mm
/gate/source/sourceBall1/gps/pos/centre 28.6 49.54 75. mm
/gate/source/addSource sourceBall2
/gate/source/sourceBall2/gps/particle gamma
/gate/source/sourceBall2/setType backtoback
/gate/source/sourceBall2/gps/ene/type Mono
/gate/source/sourceBall2/gps/ene/mono 511. keV
/gate/source/sourceBall2/setActivity 28000. becquerel
/gate/source/sourceBall2/gps/type Volume
/gate/source/sourceBall2/gps/angtype iso
/gate/source/sourceBall2/gps/shape Sphere
/gate/source/sourceBall2/gps/radius 6.5 mm
/gate/source/sourceBall2/gps/pos/centre -28.6 49.54 75. mm
/gate/source/addSource sourceBall3
/gate/source/sourceBall3/gps/particle gamma
/gate/source/sourceBall3/setType backtoback
/gate/source/sourceBall3/gps/ene/type Mono
/gate/source/sourceBall3/gps/ene/mono 511. keV
/gate/source/sourceBall3/setActivity 63000. becquerel
/gate/source/sourceBall3/gps/type Volume
/gate/source/sourceBall3/gps/angtype iso
/gate/source/sourceBall3/gps/shape Sphere
/gate/source/sourceBall3/gps/radius 8.5 mm
/gate/source/sourceBall3/gps/pos/centre -57.2 0. 75. mm
/gate/source/addSource sourceBall4
/gate/source/sourceBall4/gps/particle gamma
/gate/source/sourceBall4/setType backtoback
/gate/source/sourceBall4/gps/ene/type Mono
/gate/source/sourceBall4/gps/ene/mono 511. keV
/gate/source/sourceBall4/setActivity 137000. becquerel
/gate/source/sourceBall4/gps/type Volume
/gate/source/sourceBall4/gps/angtype iso
/gate/source/sourceBall4/gps/shape Sphere
/gate/source/sourceBall4/gps/radius 11. mm
/gate/source/sourceBall4/gps/pos/centre -28.6 -49.54 75. mm
/gate/source/addSource sourceBall5
/gate/source/sourceBall5/gps/particle gamma
/gate/source/sourceBall5/setType backtoback
/gate/source/sourceBall5/gps/ene/type Mono
/gate/source/sourceBall5/gps/ene/mono 511. keV
/gate/source/sourceBall5/setActivity 282000. becquerel
/gate/source/sourceBall5/gps/type Volume
/gate/source/sourceBall5/gps/angtype iso
/gate/source/sourceBall5/gps/shape Sphere
/gate/source/sourceBall5/gps/radius 14. mm
/gate/source/sourceBall5/gps/pos/centre 28.6 -49.54 75. mm
/gate/source/addSource sourceBall6
/gate/source/sourceBall6/gps/particle gamma
/gate/source/sourceBall6/setType backtoback
/gate/source/sourceBall6/gps/ene/type Mono
/gate/source/sourceBall6/gps/ene/mono 511. keV
/gate/source/sourceBall6/setActivity 652000. becquerel
/gate/source/sourceBall6/gps/type Volume
/gate/source/sourceBall6/gps/angtype iso
/gate/source/sourceBall6/gps/shape Sphere
/gate/source/sourceBall6/gps/radius 18.5 mm
/gate/source/sourceBall6/gps/pos/centre 57.2 0. 75. mm

/vis/disable

/gate/output/root/setFileName ../../calculTOF_outputs/GateOutputs/TOF_phantom8
/gate/output/root/setRootHitFlag 1
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setRootCoincidencesFlag 1
/gate/random/setEngineName MersenneTwister

/gate/application/setTimeSlice 1 s
/gate/application/setTimeStart 0. s
/gate/application/setTimeStop 1 s
/gate/random/setEngineSeed 807324911722377333
/gate/output/root/enable
/gate/application/startDAQCluster 0.4375 0.5 0 s

