/vis/disable
/gate/geometry/setMaterialDatabase GateMaterials.db
/gate/geometry/setMaterialDatabase ClMind_GateMaterials.db
/gate/world/geometry/setXLength 1000. mm
/gate/world/geometry/setYLength 1000. mm
/gate/world/geometry/setZLength 1000. mm
/gate/world/vis/setVisible 1
/gate/world/setMaterial Air
/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/placement/setTranslation 0.0 0.0 0.0 cm
/gate/cylindricalPET/geometry/setRmax 48. cm
/gate/cylindricalPET/geometry/setRmin 2. cm
/gate/cylindricalPET/geometry/setHeight 20. cm
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/vis/forceWireframe
/gate/cylindricalPET/vis/setColor red
/gate/cylindricalPET/vis/setVisible 0
/gate/cylindricalPET/daughters/name head
/gate/cylindricalPET/daughters/insert box
/gate/head/placement/setTranslation 30. 0.0 0.0 cm
/gate/head/geometry/setXLength 22. mm
/gate/head/geometry/setYLength 100. mm
/gate/head/geometry/setZLength 100. mm
/gate/head/setMaterial Air
/gate/head/vis/setColor white
/gate/head/vis/setVisible 0
/gate/head/daughters/name Detector
/gate/head/daughters/insert box
/gate/Detector/placement/setTranslation 0. 0. 0. cm
/gate/Detector/geometry/setXLength 22. mm
/gate/Detector/geometry/setYLength 100. mm
/gate/Detector/geometry/setZLength 100. mm
/gate/Detector/setMaterial Air
/gate/Detector/vis/setColor yellow
/gate/Detector/vis/setVisible 0
/gate/Detector/vis/forceWireframe
/gate/Detector/daughters/name Coating_Layer
/gate/Detector/daughters/insert box
/gate/Coating_Layer/placement/setTranslation -10.0005 0.0 0.0 mm
/gate/Coating_Layer/geometry/setXLength 1000. nm
/gate/Coating_Layer/geometry/setYLength 100. mm
/gate/Coating_Layer/geometry/setZLength 100. mm
/gate/Coating_Layer/setMaterial PbW04_Black
/gate/Coating_Layer/vis/setColor black
/gate/Coating_Layer/vis/setVisible 1
/gate/Detector/daughters/name PbWO4_crystal
/gate/Detector/daughters/insert box
/gate/PbWO4_crystal/placement/setTranslation 0. 0. 0. cm
/gate/PbWO4_crystal/geometry/setXLength 20. mm
/gate/PbWO4_crystal/geometry/setYLength 100. mm
/gate/PbWO4_crystal/geometry/setZLength 100. mm
/gate/PbWO4_crystal/setMaterial PbW04_Y
/gate/PbWO4_crystal/vis/setColor blue
/gate/PbWO4_crystal/vis/setVisible 1
/gate/PbWO4_crystal/vis/forceWireframe
/gate/Detector/daughters/name PhotElec_Layer
/gate/Detector/daughters/insert box
/gate/PhotElec_Layer/placement/setTranslation 10.0000125 0.0 0.0 mm
/gate/PhotElec_Layer/geometry/setXLength 25. nm
/gate/PhotElec_Layer/geometry/setYLength 100. mm
/gate/PhotElec_Layer/geometry/setZLength 100. mm
/gate/PhotElec_Layer/setMaterial Bialkali_Bleu
/gate/PhotElec_Layer/vis/setColor red
/gate/PhotElec_Layer/vis/setVisible 1
/gate/systems/cylindricalPET/rsector/attach head
/gate/systems/cylindricalPET/crystal/attach Detector
/gate/systems/cylindricalPET/layer0/attach Coating_Layer
/gate/systems/cylindricalPET/layer1/attach PbWO4_crystal
/gate/systems/cylindricalPET/layer2/attach PhotElec_Layer
/gate/PbWO4_crystal/attachCrystalSD
/gate/PhotElec_Layer/attachCrystalSD
/gate/Coating_Layer/attachCrystalSD
/gate/systems/cylindricalPET/describe

/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel
/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel
/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel
/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+
/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+
/gate/physics/addProcess PositronAnnihilation
/gate/physics/addProcess eMultipleScattering e+
/gate/physics/addProcess eMultipleScattering e-
/gate/physics/addProcess Cerenkov
/gate/physics/addProcess Scintillation
/gate/physics/addProcess OpticalAbsorption
/gate/physics/addProcess OpticalRayleigh
/gate/physics/addProcess OpticalBoundary
/gate/physics/addProcess OpticalMie
/gate/physics/addProcess OpticalWLS
/gate/physics/processList Enabled
/gate/physics/processList Initialized

/gate/run/initialize
/gate/source/addSource flash
/gate/source/flash/gps/particle gamma
/gate/source/flash/gps/ene/type Mono
/gate/source/flash/gps/ene/mono 511. keV
/gate/source/flash/setActivity 500000. becquerel
/gate/source/flash/gps/pos/centre 0. 0. 0. cm
/gate/source/flash/gps/ang/mintheta 90. deg
/gate/source/flash/gps/ang/maxtheta 90. deg
/gate/source/flash/gps/ang/minphi 180. deg
/gate/source/flash/gps/ang/maxphi 180. deg
/gate/source/flash/gps/direction 1 0 0
/gate/source/list


/gate/output/root/setFileName ../../calculTOF_outputs/GateOutputs/test13
/gate/output/root/setRootHitFlag 1
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setRootCoincidencesFlag 1
/gate/random/setEngineName MersenneTwister

/gate/application/setTimeSlice 1 s
/gate/application/setTimeStart 0. s
/gate/application/setTimeStop 1 s
/gate/random/setEngineSeed 1423713531208034439
/gate/output/root/enable
/gate/application/startDAQCluster 0.75 0.8125 0 s

