# capillaire
/gate/world/daughters/name                             capillaire1
/gate/world/daughters/insert                           cylinder
/gate/capillaire1/geometry/setRmin                   200.  um
/gate/capillaire1/geometry/setRmax                   700. um
/gate/capillaire1/geometry/setHeight                 50. mm
/gate/capillaire1/placement/setTranslation           1. 0. 0. cm
/gate/capillaire1/setMaterial                        Glass
/gate/capillaire1/attachPhantomSD

# filled with water
/gate/world/daughters/name                     capillaire1_water
/gate/world/daughters/insert                   cylinder
/gate/capillaire1_water/geometry/setRmin                      0. um
/gate/capillaire1_water/geometry/setRmax                      200. um
/gate/capillaire1_water/geometry/setHeight                    50. mm
/gate/capillaire1_water/setMaterial                           Water
/gate/capillaire1_water/placement/setTranslation                    1. 0. 0. cm
/gate/capillaire1_water/attachPhantomSD

# capillaire
/gate/world/daughters/name                             capillaire2
/gate/world/daughters/insert                           cylinder
/gate/capillaire2/geometry/setRmin                   200.  um
/gate/capillaire2/geometry/setRmax                   700. um
/gate/capillaire2/geometry/setHeight                 50. mm
/gate/capillaire2/placement/setTranslation           5. 0. 0. cm
/gate/capillaire2/setMaterial                        Glass
/gate/capillaire2/attachPhantomSD

#filled with water
/gate/world/daughters/name                     capillaire2_water
/gate/world/daughters/insert                   cylinder
/gate/capillaire2_water/geometry/setRmin                      0. um
/gate/capillaire2_water/geometry/setRmax                      200. um
/gate/capillaire2_water/geometry/setHeight                    50. mm
/gate/capillaire2_water/setMaterial                           Water
/gate/capillaire2_water/placement/setTranslation                    5. 0. 0. cm
/gate/capillaire2_water/attachPhantomSD

# capillaire
/gate/world/daughters/name                             capillaire3
/gate/world/daughters/insert                           cylinder
/gate/capillaire3/geometry/setRmin                   200.  um
/gate/capillaire3/geometry/setRmax                   700. um
/gate/capillaire3/geometry/setHeight                 50. mm
/gate/capillaire3/placement/setTranslation           8. 0. 0. cm
/gate/capillaire3/setMaterial                        Glass
/gate/capillaire3/attachPhantomSD

# filled with water
/gate/world/daughters/name                     capillaire3_water
/gate/world/daughters/insert                   cylinder
/gate/capillaire3_water/geometry/setRmin                      0. um
/gate/capillaire3_water/geometry/setRmax                      200. um
/gate/capillaire3_water/geometry/setHeight                    50. mm
/gate/capillaire3_water/setMaterial                           Water
/gate/capillaire3_water/placement/setTranslation                    8. 0. 0. cm
/gate/capillaire3_water/attachPhantomSD


# capillaire
/gate/world/daughters/name                             capillaire4
/gate/world/daughters/insert                           cylinder
/gate/capillaire4/geometry/setRmin                   200.  um
/gate/capillaire4/geometry/setRmax                   700. um
/gate/capillaire4/geometry/setHeight                 50. mm
/gate/capillaire4/placement/setTranslation           11. 0. 0. cm
/gate/capillaire4/setMaterial                        Glass
/gate/capillaire4/attachPhantomSD

# filled with water
/gate/world/daughters/name                     capillaire4_water
/gate/world/daughters/insert                   cylinder
/gate/capillaire4_water/geometry/setRmin                      0. um
/gate/capillaire4_water/geometry/setRmax                      200. um
/gate/capillaire4_water/geometry/setHeight                    50. mm
/gate/capillaire4_water/setMaterial                           Water
/gate/capillaire4_water/placement/setTranslation                    11. 0. 0. cm
/gate/capillaire4_water/attachPhantomSD

# capillaire
/gate/world/daughters/name                             capillaire5
/gate/world/daughters/insert                           cylinder
/gate/capillaire5/geometry/setRmin                   200.  um
/gate/capillaire5/geometry/setRmax                   700. um
/gate/capillaire5/geometry/setHeight                 50. mm
/gate/capillaire5/placement/setTranslation           14. 0. 0. cm
/gate/capillaire5/setMaterial                        Glass
/gate/capillaire5/attachPhantomSD

# filled with water
/gate/world/daughters/name                     capillaire5_water
/gate/world/daughters/insert                   cylinder
/gate/capillaire5_water/geometry/setRmin                      0. um
/gate/capillaire5_water/geometry/setRmax                      200. um
/gate/capillaire5_water/geometry/setHeight                    50. mm
/gate/capillaire5_water/setMaterial                           Water
/gate/capillaire5_water/placement/setTranslation                    14. 0. 0. cm
/gate/capillaire5_water/attachPhantomSD


# capillaire
/gate/world/daughters/name                             capillaire_m1
/gate/world/daughters/insert                           cylinder
/gate/capillaire_m1/geometry/setRmin                   200.  um
/gate/capillaire_m1/geometry/setRmax                   700. um
/gate/capillaire_m1/geometry/setHeight                 50. mm
/gate/capillaire_m1/placement/setTranslation           -5. 0. 0. cm
/gate/capillaire_m1/setMaterial                        Glass
/gate/capillaire_m1/attachPhantomSD

# filled with water
/gate/world/daughters/name                     capillaire_m1_water
/gate/world/daughters/insert                   cylinder
/gate/capillaire_m1_water/geometry/setRmin                      0. um
/gate/capillaire_m1_water/geometry/setRmax                      200. um
/gate/capillaire_m1_water/geometry/setHeight                    50. mm
/gate/capillaire_m1_water/setMaterial                           Water
/gate/capillaire_m1_water/placement/setTranslation                    -5. 0. 0. cm
/gate/capillaire_m1_water/attachPhantomSD


# capillaire
/gate/world/daughters/name                             capillaire_m2
/gate/world/daughters/insert                           cylinder
/gate/capillaire_m2/geometry/setRmin                   200.  um
/gate/capillaire_m2/geometry/setRmax                   700. um
/gate/capillaire_m2/geometry/setHeight                 50. mm
/gate/capillaire_m2/placement/setTranslation           -8. 0. 0. cm
/gate/capillaire_m2/setMaterial                        Glass
/gate/capillaire_m2/attachPhantomSD

# filled with water
/gate/world/daughters/name                     capillaire_m2_water
/gate/world/daughters/insert                   cylinder
/gate/capillaire_m2_water/geometry/setRmin                      0. um
/gate/capillaire_m2_water/geometry/setRmax                      200. um
/gate/capillaire_m2_water/geometry/setHeight                    50. mm
/gate/capillaire_m2_water/setMaterial                           Water
/gate/capillaire_m2_water/placement/setTranslation                    -8. 0. 0. cm
/gate/capillaire_m2_water/attachPhantomSD


# capillaire
/gate/world/daughters/name                             capillaire_m3
/gate/world/daughters/insert                           cylinder
/gate/capillaire_m3/geometry/setRmin                   200.  um
/gate/capillaire_m3/geometry/setRmax                   700. um
/gate/capillaire_m3/geometry/setHeight                 50. mm
/gate/capillaire_m3/placement/setTranslation           -11. 0. 0. cm
/gate/capillaire_m3/setMaterial                        Glass
/gate/capillaire_m3/attachPhantomSD

# filled with water
/gate/world/daughters/name                     capillaire_m3_water
/gate/world/daughters/insert                   cylinder
/gate/capillaire_m3_water/geometry/setRmin                      0. um
/gate/capillaire_m3_water/geometry/setRmax                      200. um
/gate/capillaire_m3_water/geometry/setHeight                    50. mm
/gate/capillaire_m3_water/setMaterial                           Water
/gate/capillaire_m3_water/placement/setTranslation                    -11. 0. 0. cm
/gate/capillaire_m3_water/attachPhantomSD


# capillaire
/gate/world/daughters/name                             capillaire_m4
/gate/world/daughters/insert                           cylinder
/gate/capillaire_m4/geometry/setRmin                   200.  um
/gate/capillaire_m4/geometry/setRmax                   700. um
/gate/capillaire_m4/geometry/setHeight                 50. mm
/gate/capillaire_m4/placement/setTranslation           -14. 0. 0. cm
/gate/capillaire_m4/setMaterial                        Glass
/gate/capillaire_m4/attachPhantomSD

# filled with water
/gate/world/daughters/name                     capillaire_m4_water
/gate/world/daughters/insert                   cylinder
/gate/capillaire_m4_water/geometry/setRmin                      0. um
/gate/capillaire_m4_water/geometry/setRmax                      200. um
/gate/capillaire_m4_water/geometry/setHeight                    50. mm
/gate/capillaire_m4_water/setMaterial                           Water
/gate/capillaire_m4_water/placement/setTranslation                    -14. 0. 0. cm
/gate/capillaire_m4_water/attachPhantomSD
